### PR TITLE
Add fallback for sha1

### PR DESCRIPTION
**Pull request by arslanashraf7**
#### What are the relevant tickets?
#59 

#### What's this PR do?
- Adds fallback to support sha1

#### How should this be manually tested?
- Git AutoRelod with URLs having sha256 or sha1 in their header 

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

#### What GIF best describes this PR or how it makes you feel?
(Optional)

### CODE REVIEW

**Comment by arslanashraf7** [comment]
@blarghmatey Can you take a look at the PR and let me know if you think we need to make other changes as well?

**Comment by blarghmatey** [comment]
Looks good to me. That should be all we need to make it work with GitHub Enterprise

**Comment by arslanashraf7** [comment]
@blarghmatey Do we have an instance where we can install the edx-sysadmin from this branch and test, Or should i go ahead and merge and test these with a new sysadmin version out?

**Comment by blarghmatey** [comment]
I can run a build from this branch for testing out the updated logic.

**Comment by arslanashraf7** [comment]
> I can run a build from this branch for testing out the updated logic.

@blarghmatey Great, Thanks! let me know if you see any issues.

**Comment by arslanashraf7** [comment]
Notified by @blarghmatey on a call that it worked so, I'm going to merge it.

**Pull request merged**
