### PR TITLE
Add Git import and Gitlogs code

### PR DESCRIPTION
**Pull request by umarmughal824**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
#4  

#### What's this PR do?
Add Git import and logs code (just moving the code from OpenEdx)

#### How should this be manually tested?
Either run through the management command like
`python manage.py lms git_add_course https://github.com/edx/edx4edx_lite.git`
or the below method
1. Just see that import courses are showing in the Git Logs
2. See the logs are also showing
3. I have used that [course](https://github.com/edx/edx4edx_lite.git) if you are willing to use the same course 

#### Where should the reviewer start?
1. Enable Sysadmin dashboard by `ENABLE_SYSADMIN_DASHBOARD` to `True`
2. Add course from old sysadmin through Course tab
Screenshot 2021-03-24 at 18 53 17

2. switch back to this sysadmin version after setting `ENABLE_SYSADMIN_DASHBOARD` to `False`

3. And see that the Git Logs tab with logs

#### Any background context you want to provide?
I suppose that Loading new courses from Github should be a part of `Courses` that should have been covered already in [Course Ticket](https://github.com/mitodl/edx-sysadmin/issues/3) that but not yet. So I will be putting up a separate PR for that.

#### Screenshots (if appropriate)
Screenshot 2021-03-25 at 14 29 36
Screenshot 2021-03-25 at 14 29 51
Screenshot 2021-03-25 at 14 30 06
Screenshot 2021-03-25 at 14 30 16
Screenshot 2021-03-25 at 14 30 23

### CODE REVIEW

**Comment by umarmughal824** [comment]
@pdpinch could you please review the screenshots? I need to confirm we are not missing anything.

**Comment by pdpinch** [comment]
The screenshots look good, and I think they are complete.

**Review by ziafazal — CHANGES_REQUESTED** [review]
@umarmughal824 there are few minor things. See inline comments.

However couple of things which can be done later
Remove mongoengine dependency and save Gitlogs to RDBMS(mysql) instead of mongo
Fix unit test and enable them on CI

**Review by ziafazal — APPROVED** [review]
👍

**Comment by umarmughal824** [comment]
@ziafazal bhai it's not working with the `from opaque_keys.edx.django.models import CourseKeyField` so I am reverting it back to `from xmodule.modulestore.mongoengine_fields import CourseKeyField`.

Here is the trackbook of the error
```
edx.devstack.lms                  |   from third_party_auth.provider import Registry
edx.devstack.lms                  |
edx.devstack.lms                  | Traceback (most recent call last):
edx.devstack.lms                  |   File "/edx/app/edxapp/edx-platform/manage.py", line 120, in <module>
edx.devstack.lms                  |     startup.run()
edx.devstack.lms                  |   File "/edx/app/edxapp/edx-platform/lms/startup.py", line 20, in run
edx.devstack.lms                  |     django.setup()
edx.devstack.lms                  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
edx.devstack.lms                  |     apps.populate(settings.INSTALLED_APPS)
edx.devstack.lms                  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
edx.devstack.lms                  |     app_config.import_models()
edx.devstack.lms                  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
edx.devstack.lms                  |     self.models_module = import_module(models_module_name)
edx.devstack.lms                  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/importlib/__init__.py", line 127, in import_module
edx.devstack.lms                  |     return _bootstrap._gcd_import(name[level:], package, level)
edx.devstack.lms                  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
edx.devstack.lms                  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
edx.devstack.lms                  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
edx.devstack.lms                  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
edx.devstack.lms                  |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
edx.devstack.lms                  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
edx.devstack.lms                  |   File "/edx/src/edx-sysadmin/edx_sysadmin/models.py", line 10, in <module>
edx.devstack.lms                  |     class CourseImportLog(mongoengine.Document):
edx.devstack.lms                  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mongoengine/base/metaclasses.py", line 367, in __new__
edx.devstack.lms                  |     meta["index_specs"] = new_class._build_index_specs(meta["indexes"])
edx.devstack.lms                  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mongoengine/base/document.py", line 816, in _build_index_specs
edx.devstack.lms                  |     index_specs = [cls._build_index_spec(spec) for spec in meta_indexes]
edx.devstack.lms                  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mongoengine/base/document.py", line 816, in <listcomp>
edx.devstack.lms                  |     index_specs = [cls._build_index_spec(spec) for spec in meta_indexes]
edx.devstack.lms                  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mongoengine/base/document.py", line 906, in _build_index_spec
edx.devstack.lms                  |     fields = cls._lookup_field(parts)
edx.devstack.lms                  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mongoengine/base/document.py", line 1100, in _lookup_field
edx.devstack.lms                  |     raise LookUpError('Cannot resolve field "%s"' % field_name)
edx.devstack.lms                  | mongoengine.errors.LookUpError: Cannot resolve field "course_id"
edx.devstack.lms                  | 2021-03-26 10:59:10,792 WARNING 1314 [py.warnings] [user None] [ip None] warnings.py:109 - /edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/newrelic/console.py:84: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
edx.devstack.lms                  |   prototype = wrapper.__name__[3:] + ' ' + inspect.formatargspec(
edx.devstack.lms                  |
edx.devstack.lms                  | 2021-03-26 10:59:15,786 WARNING 1314 [py.warnings] [user None] [ip None] warnings.py:109 - /edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/enterprise/tpa_pipeline.py:23: DeprecatedEdxPlatformImportWarning: Importing third_party_auth instead of common.djangoapps.third_party_auth is deprecated
edx.devstack.lms                  |   from third_party_auth.provider import Registry
```

**Pull request merged**
